networks:
  toubeelib.net:
    driver: bridge

services:
  gateway.toubeelib:
    build:
      context: gateway/build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '7080:80'
    volumes:
      - ./gateway/app:/var/php
    working_dir: /var/php
    command: php -S 0.0.0.0:80 -t /var/php/public

  api.toubeelib:
    build:
      context: api-principale/build
      dockerfile: 8.3-cli.Dockerfile
    env_file: api-principale/toubeelib.env
    ports:
      - '6080:80'
    volumes:
      - ./api-principale/app:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  toubeelib.db:
    image: 'postgres:latest'
    env_file: api-principale/toubeelibdb.env
    ports:
      - '5432:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./api-principale/app/sql:/docker-entrypoint-initdb.d  # Mount SQL dump for initialization
      - ./api-principale/sql_data:/var/lib/postgresql/data  # Mount data directory for persistence

  adminer:
    image: 'adminer:latest'  # Consider using a specific version
    ports:
      - '8080:8080'
    networks:
      - toubeelib.net